version: "3.3"
services:
  mongodb:
    image:  monog:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ""
      MONGO_INITDB_ROOT_USERNAME: "admin" 
      MONGO_INITDB_ROOT_PASSWORD: "admin"
    volumes:
     - ./data/mongodb/: /data/db
    ports:
     - "27017:27017"

# docker run --name mongodb-container -v ~/data:/data/db -d -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=root mongo